server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_service
    username: rahul
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: hotel-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      